### ISSUE TITLE
Deterministic version?

### ISSUE THREAD

**Issue by DavidRuhe** [leonardodalinky/fpsample#1]
Hi, thanks for your awesome work!

Is it correct that the current algorithm is not deterministic? I ran it several times on the same dataset but got slightly different results. Is the first point perhaps picked randomly? Is it possible to make the process deterministic, e.g., by starting from the 0th point?

**Comment by leonardodalinky** [comment]
Thanks for reminding me. This is a trivial question that I missed, and I would try to make a quick fix ASAP.

For an immediate solution, you could hack and invoke the core function once you have check those `assert` requirements. The 
 first point would be fixed by `start_idx`.
https://github.com/leonardodalinky/fpsample/blob/f1752e54d81a5d03fba5bc539b742df8b1ea9882/python/fpsample/wrapper.py#L125-L134
